@startuml class UML

''''''''''''''''''''''''''''''''''''''
'''''' Defining all classes ''''''''''
''''''''''''''''''''''''''''''''''''''

entity CBS {
    *id <<primary_key>>
    *regio <<names>>
    *recs <<Land | Gemeente | Wijk | Buurt>>
    *geom <<borders>>
    population_size
    demographic_info
}

entity Neighborhoods {
    *id <<primary_key>>
    *regio <<names>>
    *geometry <<borders>>
    population_size
    num_amenities
    area_size
    demographic_info
}

entity Graph_nodes {
    *id <<primary_key>>
    *degree
    *loc <<coordinates>>
    neighborhood_id <<performance>>
}

entity Graph_edges {
    *u <<primary_key>>
    *v <<primary_key>>
    *key <<primary_key>>
    *length
    *removed
    *geometry
    neighborhood_id
}

entity Graph_nodes_ped {
    *id <<primary_key>>
    *degree
    *loc <<coordinates>>
    neighborhood_id <<performance>>
}

entity Graph_edges_ped {
    *u <<primary_key>>
    *v <<primary_key>>
    *key <<primary_key>>
    *length
    *removed
    *geometry
    neighborhood_id
}

entity Graph_nodes_accessible {
    *node_id <<primary_key>>
}

entity Neighborhood_pts {
    *neighborhood_id <<primary_key>>
    *pts_id <<primary_key>>
    *pt <<coordinates>>
    *node_id
}

entity Features {
    *id <<primary_key>>,
    *element,
    *loc <<coordinates>>,
    public_transit_info
    amenity_info
}

entity Stations {
    *feature_id <<primary_key>>
    *node_id <<primary_key>>
    *location
    bus
    train
    railway
}

''''''''''''''''''''''''''''''''''''''
'''''' Defining relations ''''''''''''
''''''''''''''''''''''''''''''''''''''

CBS ||--o| Neighborhoods : pre-process

Neighborhood_pts::neighborhood_id ||--o{ Neighborhoods::id : create_pts_per_neighborhood
Neighborhood_pts::node_id ||--o| Graph_nodes_ped::id : create_pts_per_neighborhood


Graph_edges::u ||--|| Graph_nodes::id
Graph_edges::v ||--|| Graph_nodes::id
Graph_edges::neighborhood_id ||--o| Neighborhoods::id : load_network
Graph_edges_ped::u ||--|| Graph_nodes_ped::id
Graph_edges_ped::v ||--|| Graph_nodes_ped::id
Graph_edges_ped::neighborhood_id ||--o| Neighborhoods::id : load_network

Stations::feature_id ||--o| Features::id : link_busses
Stations::node_id ||--o| Graph_nodes::id : link_busses
Stations::location ||--o| Features::loc : link_busses

Graph_nodes_accessible::node_id ||--o| Graph_nodes::id : load_network

@enduml
