Deze file is nog niet compleet. Ik was gewoon een beetje algemeen aan het
brainstormen. Kan zijn dat we het volledig anders doen.

@startuml class UML

''''''''''''''''''''''''''''''''''''''
'''''' Defining all classes ''''''''''
''''''''''''''''''''''''''''''''''''''
' Main class
class data {
    kwb
    network
    void load_files()
    void pre_process()
    void run_simulation(f)
    Lst get_results()
}

' Wrapper class for the KWB. Uses duckdb extract data from csv.
' Should merge the data with the geo data. Can also be done in duckdb.
class CBS {
    duckdb
    __init(path_csv, path_geo)
    get_info1()
    get_info2()
    get_info...()
}

' Wrapper for interacting with the network
class network {
    Lst nodes
    Lst edges
}

class neighborhood {
    int population
    int size
    int males
    int females
    int Ethnicity
    float get_population_density()
    float get_ethnicity_proportions()
}

''''''''''''''''''''''''''''''''''''''
'''''' Defining relations ''''''''''''
''''''''''''''''''''''''''''''''''''''
data::network --> network
data::kwb --> CBS

network::nodes --> neighborhood


@enduml